export const GAME_CONSTANTS = {
  // Collectible Lifetimes
  TREAT_MIN_LIFETIME_MS: 3500,
  TREAT_SCALE_FACTOR_MS: 100,
  YARN_MIN_LIFETIME_MS: 3000,
  YARN_SCALE_FACTOR_MS: 100,

  // Game Timer
  INITIAL_TIME_SECONDS: 15,
  TREAT_TIME_BONUS_SECONDS: 5,

  // Scoring
  BASE_MOVE_SCORE: 10,
  YARN_SCORE_BONUS: 50,

  // Levels
  TOTAL_LEVELS: 12,
  BASE_GRID_SIZE: 4,
  MAX_GRID_SIZE: 7,
  LEVEL_TRANSITION_TIME_MS: 400,

  // Level Generation
  TARGET_DENSITY_BASE: 0.5,
  TARGET_DENSITY_INCREMENT: 0.03,
  TARGET_DENSITY_MAX: 0.9,
  MAX_COLLECTIBLES_PER_LEVEL: 3,

  // ELO
  DEFAULT_ELO: 1000,
  ELO_K_FACTOR: 32,

  // Race
  DISCONNECT_TIMEOUT_MS: 30_000,
  COUNTDOWN_SECONDS: 3,
} as const;
